### ISSUE TITLE
LicensesWedge force title as string resource

### ISSUE THREAD

**Issue by adrcotfas** [fennifith/Attribouter#61]
Hi,
Is something like this possible with the current implementation? Prefixing it with "^" didn't work.

```
<me.jfenn.attribouter.wedges.LicensesWedge
        title="@string/open_source_licences" 
...
```

**Comment by fennifith** [comment]
Not sure what's going wrong here, given a quick glance at the current source this should work fine. I'll test it properly later today.

**Comment by fennifith** [comment]
I can't seem to reproduce this, it's working fine for me. Could you provide me with more information? Ex:
 
- the version of Attribouter being used
- the entire config file
- your strings.xml, in case the string doesn't actually exist
- a link to the project if it's on github

**Comment by adrcotfas** [comment]
😴 Of course, thanks!
