### ISSUE TITLE
Minification / Proguard settings

### ISSUE THREAD

**Issue by fennifith** [fennifith/Attribouter#66]
Proguard settings linked in the README are non-descriptive and incomplete. And... they don't actually work.

A possible solution could be to just `-keep class me.jfenn.attribouter.** { *; }`. But that hasn't exactly been tested. I need to do some testing with the minification settings enabled.

**Comment by deletescape** [comment]
Also with R8 you can bundle the proguard file with your library so developers using it don't actually have to do anything, that would probably be worth doing when investing time here anyways
