### ISSUE TITLE
FlexBox layout problems

### ISSUE THREAD

**Issue by fennifith** [fennifith/Attribouter#68]
It seems that the button "links" occasionally have problems asserting their dimensions within the FlexBox RecyclerView layouts they're contained in...

- Occasionally, I've opened the about page to find that *all* of the links have decided to use the smallest width possible, and the button text has wrapped to multiple lines
- Most of the time a UserDialog is opened, the links recycler will not display a second line of items regardless of whether they have wrapped to another line, even though its height is `wrap_content`. Possibly related to google/flexbox-layout#349.

**Comment by hameno** [comment]
Notice this as well:
![image](https://user-images.githubusercontent.com/365084/85948365-c9a86500-b950-11ea-874b-12dc20cb39b4.png)
on a Pixel 3a emulator API 29

**Comment by hameno** [comment]
Related (?) problem:
![image](https://user-images.githubusercontent.com/365084/85949642-48ed6700-b958-11ea-8f0d-94dbf4b784d2.png)

```xml
    <me.jfenn.attribouter.wedges.AppWedge
        description="An Android application designed to help developers by automatically adding their apps to a widget for easy launching / uninstalling / reinstalling etc."
        playStoreUrl="https://play.google.com/store/apps/details?id=de.psdev.devdrawer"
        repo="github:PSDev/DevDrawer" />
```

Related question: On https://github.com/fennifith/Attribouter/wiki/AppWedge it says, that the play store link should get automatically generated, but I still had to manually enter the url for the button/icon to show.

**Comment by fennifith** [comment]
Huh. Yeah, it looks like the AppWedge isn't quite built to work with less than four links. If it's possible for you to, err, find another two, then it might work... lol

Created #70 to track this; not a major amount of work to fix, but I know I'm not gonna get around to it today.

> On https://github.com/fennifith/Attribouter/wiki/AppWedge it says, that the play store link should get automatically generated, but I still had to manually enter the url for the button/icon to show.

Yep, the wiki's a bit outdated right now; there were a lot of changes in the last update. I'll go over it all at some point & fix everything, but that's gonna take a while.

**Comment by hameno** [comment]
This app is in very early development, those fixes are not urgent. I'll can wait for the updates

**Comment by fennifith** [comment]
I seem to have fixed *one* of these issues by re-using the layout manager across recycled views; this should hopefully fix the squashing issues on the licenses screen.

I'm not sure what has changed since this was created, but I can no longer reproduce the problems in the UserDialog either; perhaps it was another dependency causing those issues which was updated in 08e18e1. If I don't run into any other issues, I'll close this in the next release.
